name: Build-OpenSSL-MultiArch

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - { name: "x86_64", config: "linux-x86_64" }
          - { name: "arm64",  config: "linux-aarch64" }
          - { name: "armv7",  config: "linux-armv4" }
          - { name: "i386",   config: "linux-elf" }

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential perl wget cmake ninja-build zip gcc-multilib g++-multilib

      - name: Download OpenSSL
        run: |
          wget https://www.openssl.org/source/openssl-3.3.2.tar.gz -O openssl.tar.gz
          tar -xf openssl.tar.gz
          mv openssl-* openssl

      - name: Configure for ${{ matrix.arch.name }}
        working-directory: openssl
        run: |
          ./Configure \
            ${{ matrix.arch.config }} \
            no-shared \
            --prefix=$PWD/build-${{ matrix.arch.name }} \
            --openssldir=$PWD/build-${{ matrix.arch.name }}/ssl

      - name: Build OpenSSL (${{ matrix.arch.name }})
        working-directory: openssl
        run: |
          make -j$(nproc)
          make install_sw
          cd ..
          mkdir output-${{ matrix.arch.name }}
          cp -r openssl/build-${{ matrix.arch.name }}/* output-${{ matrix.arch.name }}/
          zip -r openssl-${{ matrix.arch.name }}.zip output-${{ matrix.arch.name }}/

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: openssl-${{ matrix.arch.name }}
          path: openssl-${{ matrix.arch.name }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare ZIP list
        run: |
          ls artifacts/*/*.zip
          echo "FILES=$(ls artifacts/*/*.zip | tr '\n' ',')" >> $GITHUB_ENV

      - name: Create GitHub Release (multi-arch)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.run_number }}"
          name: "OpenSSL Multi-Architecture Build v${{ github.run_number }}"
          files: artifacts/*/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
